import { BrowserRouter, Route, Routes } from 'react-router-dom';
import './App.css';
import Admin from './components/Admin';
import MpList from './components/MpList';
import ListContext from './context/ListContext'
import { Component } from 'react';
import Cookies from 'js-cookie';

const List=[
{ 
  key:1,
  image:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Shri_Piyush_Goyal_Minister_of_Commerce_and_Industry_addressing_a_press_conference_%284%29.jpg/330px-Shri_Piyush_Goyal_Minister_of_Commerce_and_Industry_addressing_a_press_conference_%284%29.jpg",
  name:"Piyush vedprakash Goyal",
  wiki:"https://en.wikipedia.org/wiki/Piyush_Goyal",
  party:"BJP",
  youtube:"",
  X:"",
  symbol:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Bharatiya_Janata_Party_logo.svg/270px-Bharatiya_Janata_Party_logo.svg.png",
  summary:"Piyush Vedprakash Goyal (born 13 June 1964) is an Indian politician and chartered accountant serving as a cabinet minister in the Government of India, having portfolios such as Minister of Textiles, Minister of Commerce and Industry and Minister of Consumer Affairs, Food and Public Distribution. He was elevated to the Cabinet Minister position on 3 September 2017 from Maharashtra"
},
{ 
  key:2,
  image:"https://www.lokatantra.in/uploads/candidates_images/K8HXP7uA.jpg",
  name:"Gajanan Chandrakant Kirtikar",
  wiki:"https://en.wikipedia.org/wiki/Gajanan_Kirtikar",
  party:"shivsena",
  youtube:"",
  X:"",
  symbol:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Logo_of_Shiv_Sena.svg/270px-Logo_of_Shiv_Sena.svg.png",
  summary:'Gajanan Kirtikar is Leader of Shivsena and a Member of Parliament (MP) from Mumbai North West (Lok Sabha constituency) in Mumbai, Maharashtra, India.[1] He has been a Member of Legislative Assembly from Malad assembly constituency in Mumbai from 1990 to 2009'
},
{ 
  key:3,
  image:"https://res.cloudinary.com/dollmqugm/image/upload/v1710762693/siddiq_om77hg.png",
  name:"zeeshan Siddique",
  wiki:"https://en.wikipedia.org/wiki/Zeeshan_Siddique",
  party:"congress",
  youtube:"",
  X:"",
  symbol:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Indian_National_Congress_hand_logo.svg/225px-Indian_National_Congress_hand_logo.svg.png",
  summary:'Zeeshan Baba Siddique (born 3 October 1992) is an Indian politician from the Indian National Congress. He is currently a Member of the Legislative Assembly in Maharashtra Legislative Assembly.[1] & President of Mumbai Youth Congress.'
},
{ 
  key:4,
  image:"https://media.istockphoto.com/id/1200971027/vector/vector-illustration-of-indian-political-leader.jpg?s=612x612&w=0&k=20&c=BcuGix1OLdLi0Y89PlF8Nl5tvOACWkXfnDnsb-AKc8I=",
  name:"zeeshan Siddique",
  wiki:"https://en.wikipedia.org/wiki/Zeeshan_Siddique",
  party:"RP1",
  youtube:"",
  X:"",
  symbol:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Indian_National_Congress_hand_logo.svg/225px-Indian_National_Congress_hand_logo.svg.png",
  summary:'Zeeshan Baba Siddique (born 3 October 1992) is an Indian politician from the Indian National Congress. He is currently a Member of the Legislative Assembly in Maharashtra Legislative Assembly.[1] & President of Mumbai Youth Congress.'
},
{ 
  key:5,
  image:"https://media.istockphoto.com/id/1200971027/vector/vector-illustration-of-indian-political-leader.jpg?s=612x612&w=0&k=20&c=BcuGix1OLdLi0Y89PlF8Nl5tvOACWkXfnDnsb-AKc8I=",
  name:"zeeshan Siddique",
  wiki:"https://en.wikipedia.org/wiki/Zeeshan_Siddique",
  party:"RP1",
  youtube:"",
  X:"",
  symbol:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Indian_National_Congress_hand_logo.svg/225px-Indian_National_Congress_hand_logo.svg.png",
  summary:'Zeeshan Baba Siddique (born 3 October 1992) is an Indian politician from the Indian National Congress. He is currently a Member of the Legislative Assembly in Maharashtra Legislative Assembly.[1] & President of Mumbai Youth Congress.'
}

]
const data = [{"id":1,"de":[{"Amalapuram":"East Godavari"},
    {"Anakapalli":"Visakhapatnam"},
    {"Araku"	:"Srikakulam"},
    {"Bapatla":"Guntur"},
    {"Bapatla":	"Prakasam"},
    {"Chittoor":	"Chittoor"},
   {"Eluru":	"West Godavari"},
    {"Guntur":	"Guntur"},
    {"Kakinada":	"East Godavari"},
    {"Kakinada":	"Visakhapatnam"},
    {"Machilipatnam":	"West Godavari"},
    {"Machilipatnam":	"Krishna"},
    {"Narsapuram":	"East Godavari"},
    {"Narasaraopet":	"Guntur"},
    {"Nellore"	:"Nellore"},
    {"Nellore":	"Prakasam"},
    {"Ongole"	:"Prakasam"},
    {"Rajahmundry":	"East Godavari"},
    {"Rajampet"	:"Chittoor"},
    {"Srikakulam":	"Srikakulam"},
    {"Tirupati":	"Chittoor"},
    {"Tirupati"	:"Nellore"},
    {"Vijayawada":	"Krishna"},
    {"Visakhapatnam":	"Visakhapatnam"},
    {"Vizianagaram":	"Vizianagaram"}]},
    {"id": 2,"de":[{"ArunachalWest": "Arunachal West"},
        {"ArunachalEast": "ArunachalEast"}]},
    {"id":3,"de":[{"Autonomous District":	"Karbi Anglong and Dima Hasao districts"},
        {"Barpeta":"Barpeta district"},
        {"Dhubri":	"Dhubri district"},
        {"Dibrugarh"	:"Dibrugarh district"},
        {"Gauhati":	"Kamrup Metropolitan, Kamrup Rural, and Darrang districts"},
        {"Jorhat":	"Jorhat district"},
        {"Kaliabor":	"Nagaon district"},
        {"Karimganj":	"Karimganj, Hailakandi, and Cachar districts"},
        {"Lakhimpur":	"Lakhimpur district"},
        {"Mangaldoi":	"Darrang, Udalguri, and Mangaldai districts"},
        {"Nawgong"	:"Nowgong district"},
        {"Silchar":	"Cachar district"},
        {"Tezpur"	:"Sonitpur, Biswanath, and Lakhimpur districts"},
        {"Kokrajhar":"Kokrajhar, Chirang, Baksa, and Udalguri districts"}]},
        {"id":4,"de":	[{"Araria":	"Araria district"},
        {"Aurangabad":	"Aurangabad district"},
        {"Banka":"	Banka district"},
        {"Begusarai	":"Begusarai district"},
        {"Bhagalpur	":"Bhagalpur district"},
        {"Buxar	":"Buxar district"},
        {"Darbhanga":"	Darbhanga district"},
        {"Gaya":"	Gaya district"},
        {"Gopalganj	":"Gopalganj district"},
        {"Hajipur":"	Vaishali district"},
        {"Jahanabad":"	Jehanabad district"},
        {"Jamui	":"Jamui district"},
        {"Karakat":"	Rohtas district"},
        {"Katihar":"	Katihar district"},
        {"Khagaria":"	Khagaria district"},
        {"Kishanganj":"	Kishanganj district"},
        {"Madhepura	":"Madhepura district"},
        {"Madhubani	":"Madhubani district"},
        {"Maharajganj":"	Siwan district"},
        {"Munger":"	Munger district"},
        {"Muzaffarpur":"	Muzaffarpur district"},
        {"Nalanda":"	Nalanda district"},
        {"Nawada":"	Nawada district"},
        {"Paschim ":"Champaran	West Champaran district"},
        {"Patna Sahib":"	Patna district"},
        {"Pataliputra":"	Patna district"},
        {"Purvi":" Champaran	East Champaran district"},
        {"Purnia":"	Purnia district"},
        {"Rosera	":"Samastipur district"},
        {"Saharsa	":"Saharsa district"},
        {"Samastipur	":"Samastipur district"},
        {"Saran	":"Saran district"},
        {"Sasaram	":"Rohtas district"},
        {"Sheohar":"	Sheohar district"},
        {"Sitamarhi	":"Sitamarhi district"},
        {"Siwan":"	Siwan district"},
        {"Supaul":"	Supaul district"},
        {"Ujiarpur":"	Samastipur district"},
        {"Vaishali":"	Vaishali district"},
        {"Valmiki Nagar":"West Champaran"}]},
        {"id":5,"de":[{"Bastar":"	Bastar district and parts of Dantewada, and Kondagaon districts"},
        {"Bilaspur":"	Bilaspur district and parts of Bilaspur division"},
        {"Durg":"	Durg district and parts of Rajnandgaon and Durg districts"},
        {"Janjgir-Champa":"	Janjgir-Champa district and parts of Bilaspur division"},
        {"Kanker":"	Kanker district and parts of Bastar district"},
        {"Korba":"	Korba district and parts of Korba and Surguja districts"},
        {" Mahasamund":"	Mahasamund district and parts of Raipur and Mahasamund districts"},
        {" Raigarh":"	Raigarh district and parts of Raigarh district"},
        {"Raipur":"	Raipur district and parts of Dhamtari, Raipur, and Mahasamund districts"},
        {"Rajnandgaon":"	Rajnandgaon district and parts of Rajnandgaon district"},
        {"Surguja":"	Surguja district and parts of Surguja district"}]},
    {"id":6	,"de":[{"North Goa":"North Goa district"},
        {"South Goa"	:"South Goa district"}]},
    {"id":7,"de":[{"Ahmedabad East"	:"Ahmedabad district"},
        {"Ahmedabad West":"	Ahmedabad district"},
        {"Amreli":"	Amreli district and part of Bhavnagar district"},
        {"Anand	":"Anand district and part of Kheda district"},
        {"Banaskantha":"	Banaskantha district"},
        {"Bardoli	":"Surat district and part of Tapi district"},
        {"Bharuch	":"Bharuch district and part of Surat district"},
        {"Bhavnagar	":"Bhavnagar district"},
        {"Chhota Udaipur":"	Chhota Udaipur district"},
        {" Dahod	":"Dahod district"},
        {"Gandhinagar":"	Gandhinagar district"},
        {"Jamnagar	":"Jamnagar district"},
        {"Junagadh":"	Junagadh district"},
        {"Kachchh":"	Kachchh district"},
        {"Kheda	":"Kheda district and part of Anand district"},
        {"Mahesana	":"Mahesana district"},
        {" Navsari	":"Navsari district"},
        {" Panchmahal":"	Panchmahal district"},
        {"Patan	":"Patan district"},
        {"Porbandar	":"Porbandar district"},
        {"Rajkot	":"Rajkot district"},
        {"Sabarkantha":"	Sabarkantha district"},
        {"Surat	":"Surat district"},
        {"Surendranagar":"	Surendranagar district"},
        {"Vadodara	":"Vadodara district"},
        {"Valsad":"	Valsad district and part of Navsari district"}]},
    {"id":8,"de":[{"Ambala":	"Ambala district and parts of Yamunanagar district"},
    {"Bhiwani-Mahendragarh":"	Bhiwani and Mahendragarh districts"},
    {"Faridabad":"	Faridabad district"},
    {"Gurgaon":"	Gurgaon district and parts of Rewari district"},
    {"Hisar":"	Hisar district and parts of Fatehabad district"},
    {" Karnal":"	Karnal district and parts of Karnal district"},
    {"  Kurukshetra":"	Kurukshetra district and parts of Karnal district"},
    {"  Rohtak":"	Rohtak district"},
    {"  Sirsa":"	Sirsa district and parts of Fatehabad district"},
    {"  Sonipat":"	Sonipat district"}]},
    {"id":9,"de":[{"Hamirpur":"Hamirpur"},
    {"Kangra":"	Kangra"},
    {"Mandi":"Mandi"},
    {"Shimla":"	Shimla"}]},
    {"id":10,"de":	[{"Chatra":"Chatra district"},
    {"Dhanbad":"	Dhanbad district and parts of Dhanbad district"},
    {"  Dumka":"	Dumka district and parts of Dumka district"},
    {" Giridih":"	Giridih district"},
    {" Godda":"	Godda district and parts of Godda district"},
   {"Khunti":"Khunti district"},
        {"Koderma":"	Koderma district"},
        {"Lohardaga":"	Lohardaga district"},
        {"Palamu":"	Palamu district"},
        {"Ranchi":"	Ranchi district and parts of Ranchi district"},
        {"Rajmahal":"	Sahibganj district"},
        {"Singhbhum	West":" Singhbhum district and parts of West Singhbhum district"}]},
    {"id":11,"de":[{"Bagalkot":"Bagalkot district"},
    {"Bangalore Central":"	Bangalore Urban district"},
    {"Bangalore North":"	Bangalore Urban district"},
    {"Bangalore Rural":"	Bangalore Rural district"},
    {"Bangalore South":"	Bangalore Urban district"},
    {"Belgaum":"	Belgaum district"},
    {"Bellary":"	Bellary district"},
    {"Bidar	":"Bidar district"},
    {"Bijapur":"Bijapur district"},
        {"Chamarajanagar":"	Chamarajanagar district"},
        {"Chikkballapur":"	Chikkaballapur district"},
        {"Chikkodi":"	Belgaum district"},
        {"Chitradurga":"	Chitradurga district"},
        {"Dakshina Kannada":"	Dakshina Kannada district"},
        {"Davanagere":"	Davanagere district"},
        {"Dharwad":"	Dharwad district"},
        {"Gulbarga":"	Gulbarga district"},
        {" Hassan":"	Hassan district"},
        {"Haveri":"	Haveri district"},
        {"Kolar":"	Kolar district"},
        {"Koppal":"	Koppal district"},
        {"Mandya":"	Mandya district"},
        {"Mysore":"	Mysore district"},
        {"Raichur":"	Raichur district"},
        {"Shimoga":"	Shimoga district"},
        {"Tumkur":"	Tumkur district"},
        {"Udupi Chikmagalur":"	Udupi and Chikmagalur districts"},
        {"Uttara Kannada":"	Uttara Kannada district"}]},
    {"id":12,"de":	[{"Alappuzha":"Alappuzha district"},
    {"Attingal":"	Thiruvananthapuram district"},
    {"Chalakudy	":"Thrissur district and parts of Ernakulam district"},
    {"Ernakulam	":"Ernakulam district"},
    {"Idukki":"	Idukki district and parts of Kottayam district"},
    {"Kannur":"	Kannur district"},
    {"Kasaragod":"	Kasaragod district"},
    {"Kollam":"	Kollam district"},
    {"Kottayam":"	Kottayam district"},
    {"Kozhikode":"	Kozhikode district"},
    {"Malappuram":"	Malappuram district"},
    {"Mavelikkara":"	Alappuzha district and parts of Kollam district"},
    {"Palakkad":"	Palakkad district"},
    {"Pathanamthitta":"	Pathanamthitta district"},
    {" Ponnani":"	Malappuram district"},
    {"Thiruvananthapuram":"Thiruvananthapuram district"},
        {"Thrissur":"	Thrissur district"},
        {"Vadakara":"	Kozhikode district and parts of Kannur district"},
        {"Wayanad  ":"	Wayanad"},
        {"Thiruvalla ":"	Pathanamthitta"}]},
    {"id":13,"de":[{"Balaghat":"Balaghat"},
    {"Balaghat-ST":"	Balaghat"},
    {"Betul":"	Betul"},
    {"Bhopal":"	Bhopal"},
    {"Bhind":"	Bhind"},
    {"Chhindwara":"	Chhindwara"},
    {"Damoh":"	Damoh"},
    {"Dewas	":"Dewas"},
    {"Dhar":"	Dhar"},
    {"Hoshangabad":"	Hoshangabad"},
    {"Indore":"	Indore"},
    {"Jabalpur":"	Jabalpur"},
    {"Khandwa":"	Khandwa"},
    {"Khargone":"	Khargone"},
    {"Khajuraho":"	Chhatarpur"},
    {"Mandsaur":"	Mandsaur"},
    {"Mandla":"	Mandla"},
    {"Morena":"	Morena"},
    {"Narsinghpur":"	Narsinghpur"},
    {"Rajgarh":"	Rajgarh"},
    {"Ratlam":"	Ratlam"},
    {"Rewa":"	Rewa"},
    {"Satna":"	Satna"},
    {"Seoni	":"Seoni"},
    {"Shahdol":"	Shahdol"},
    {"Sidhi":"	Sidhi"},
    {"Tikamgarh":"	Tikamgarh"},
    {"Ujjain":"	Ujjain"},
        {"Vidisha":"	Vidisha"}]},
    {"id":14,"de":[{"Ahmednagar"	:"Ahmednagar district"},
    {"Akola":"	Akola district"},
    {"Amravati":"	Amravati district"},
    {"Aurangabad":"	Aurangabad district"},
    {" Baramati":"	Pune district"},
    {" Beed":"	Beed district"},
    {"Bhandara-Gondiya":"	Bhandara and Gondia districts"},
    {"Bhiwandi":"	Thane district"},
    {"Buldhana":"	Buldhana district"},
    {"Chandrapur":"	Chandrapur district"},
    {"Dhule":"	Dhule district"},
    {"Dindori":"	Nashik district"},
    {"Gadchiroli-Chimur":"	Gadchiroli and parts of Chandrapur district"},
    {"Hatkanangle":"	Kolhapur district"},
    {"Hingoli":"	Hingoli district"},
    {" Jalgaon":"	Jalgaon district"},
    {"Jalna":"Jalna district"},
        {"Kalyan":"	Thane district"},
        {"Kolhapur":"	Kolhapur district"},
        {"Latur":"	Latur district"},
        {"Madha":"	Solapur district"},
        {"Maval":"	Pune district"},
        {"Mumbai North":"	Mumbai suburban district"},
        {"Mumbai North Central":"	Mumbai suburban district"},
        {"Mumbai North East	":"Mumbai suburban district"},
        {"Mumbai North West":"	Mumbai suburban district"},
        {"Mumbai South":"	Mumbai district"},
        {"Mumbai South Central":"	Mumbai suburban district"},
        {"Nagpur":"	Nagpur district"},
        {"Nanded":"	Nanded district"},
        {"Nandurbar":"	Nandurbar district"},
        {"Nashik":"	Nashik district"},
        {"Osmanabad":"	Osmanabad district"},
        {"Palghar":"	Palghar district"},
        {"Parbhani":"	Parbhani district"},
        {"Pune":"	Pune district"},
        {"Raigad":"	Raigad district"},
        {"Ramtek":"	Nagpur district"},
        {"Ratnagiri-Sindhudurg":"	Ratnagiri and Sindhudurg districts"},
        {"Raver":"	Jalgaon district"},
        {"Sangli":"	Sangli district"},
        {"Satara":"	Satara district"},
        {"Shirdi":"	Ahmednagar district"},
        {"Shirur":"	Pune district"},
        {"Solapur":"	Solapur district"},
        {"Thane":"	Thane district"},
        {"Wardha":"	Wardha district"},
        {"Yavatmal-Washim":"	Yavatmal and Washim districts"}]},
    {"id":15,"de":[{"Inner Manipur":"Imphal East and Imphal West districts"},
    {"Outer Manipur":	"Chandel, Churachandpur, Senapati, Tamenglong, Ukhrul, and parts of Thoubal and Kangpokpi districts"}]},
    {"id":16,"de":[{"Shillong":"East Khasi Hills, West Khasi Hills, South West Khasi Hills, and Ri Bhoi districts"},
    {"Tura	West":"Garo Hills, East Garo Hills, South Garo Hills, and North Garo Hills districts"}]},
    {"id":17,"de":[{"Mizoram":	"All districts of Mizoram"}]},
    {"id":18,"de":[{"Nagaland":"All districts of Nagaland"}]},
    {"id":19,"de":[{"Aska":	"Ganjam district"},
    {" Balasore":"	Balasore district"},
    {" Bargarh":"	Bargarh district"},
    {"Berhampur":"	Ganjam district"},
    {"Bhadrak":"	Bhadrak district"},
    {"Bhubaneswar":"	Khordha district"},
    {"Bolangir":"	Bolangir district"},
    {"Cuttack":"	Cuttack district"},
    {"Dhenkanal	":"Dhenkanal district"},
    {"Jagatsinghpur":"	Jagatsinghpur district"},
    {"Jajpur":"	Jajpur district"},
    {"Kandhamal":"	Kandhamal district"},
    {"Kendrapara":"	Kendrapara district"},
    {"Keonjhar":"	Keonjhar district"},
    {"Koraput":"	Koraput district"},
    {"Mayurbhanj":"	Mayurbhanj district"},
    {"Nabarangpur":"	Nabarangpur district"},
    {"Puri":"	Puri district"},
    {"Sambalpur":"	Sambalpur district"},
    {"Sundargarh":"	Sundargarh district"},
    {" Kalahandi":"	Kalahandi district"}]},
    {"id":20,"de":[{"Amritsar":"Amritsar district"},
    {"Anandpur Sahib":"Rupnagar, and parts of Nawanshahr and Mohali districts"},
    {"Bathinda":"	Bathinda district"},
    {"Faridkot":"	Faridkot district"},
    {"Fatehgarh Sahib":"	Fatehgarh Sahib district"},
    {"Ferozepur":"	Ferozepur district"},
    {"Gurdaspur":"	Gurdaspur district"},
    {"Hoshiarpur":"	Hoshiarpur district"},
    {"Jalandhar":"	Jalandhar district"},
    {"Khadoor Sahib":"	Tarn Taran district"},
    {"Ludhiana":"	Ludhiana district"},
    {"Patiala":"	Patiala district"},
        {"Sangrur":"	Sangrur district"}]},
    {"id":21,"de":[{"Ajmer":"Ajmer distric"},
    {"Alwar":"	Alwar district"},
        {" Banswara":"	Banswara district"},
        {" Barmer":"	Barmer district"},
        {"Bhilwara":"	Bhilwara district"},
        {"Chittorgarh":"	Chittorgarh district"},
        {"Churu":"	Churu district"},
        {"Dausa":"	Dausa district"},
        {"Ganganagar":"	Ganganagar district"},
        {"Jaipur":"	Jaipur district"},
        {"Jaipur Rural":"	Jaipur district"},
        {"Jalore":"	Jalore district"},
        {"Jhalawar-Baran":"	Jhalawar and Baran districts"},
        {"Jhunjhunu":"	Jhunjhunu district"},
        {"Jodhpur":"	Jodhpur district"},
        {"Karauli-Dholpur":"	Karauli and Dholpur districts"},
        {"Kota":"	Kota district"},
        {"Nagaur":"	Nagaur district"},
        {"Pali":"	Pali district"},
        {"Rajsamand":"	Rajsamand district"},
        {"Sikar":"	Sikar district"},
        {"Tonk-Sawai Madhopur":"	Tonk and Sawai Madhopur districts"},
        {"Udaipur":"	Udaipur district"},
        {"Bharatpur":"	Bharatpur district"},
        {"Gwalior":"	Gwalior district"}]},
    {"id":22,"de":[{"Sikkim"	:"All districts of Sikkim"}]},
    {"id":23,"de":[{"Tamilnadu":	"Chennai Central	Chennai Chennai North	Chennai"},
        {"Chennai ":"South	Chennai"},
        {"Sriperumbudur":"	Kancheepuram"},
        {"Kancheepuram":"	Kancheepuram"},
        {"Arakkonam	":"Vellore"},
        {"Vellore":"	Vellore"},
        {"Krishnagiri":"	Krishnagiri"},
        {"Dharmapuri":"	Dharmapuri"},
        {"Tiruvannamalai":"	Tiruvannamalai"},
        {"Arani":"	Tiruvannamalai"},
        {"Viluppuram":"	Viluppuram"},
        {"Kallakurichi":"	Viluppuram"},
        {"Salem":"	Salem"},
        {"Namakkal":"	Namakkal"},
        {"Erode":"	Erode"},
        {"Tiruppur":"	Tiruppur"},
        {"Nilgiris":"	Nilgiris"},
        {"Coimbatore":"	Coimbatore"},
        {"Pollachi":"	Coimbatore"},
        {"Dindigul":"	Dindigul"},
        {"Karur":"	Karur"},
        {"Tiruchirappalli":"	Tiruchirappalli"},
        {"Perambalur":"	Perambalur"},
        {"Cuddalore":"	Cuddalore"},
        {"Chidambaram":"	Cuddalore"},
        {"Mayiladuthurai":"	Mayiladuthurai"},
        {"Nagapattinam":"	Nagapattinam"},
        {"Thanjavur":"	Thanjavur"},
        {"Sivaganga":"	Sivaganga"},
        {"Madurai":"	Madurai"},
        {"Theni":"	Theni"},
        {"Virudhunagar":"	Virudhunagar"},
        {"Ramanathapuram":"	Ramanathapuram"},
        {"Thoothukkudi":"	Thoothukkudi"},
        {"Tenkasi":"	Tenkasi"},
        {"Tirunelveli":"	Tirunelveli"},
        {"Kanniyakumari":"	Kanniyakumari"}]},
    {"id":24,"de":[{"Adilabad":"Adilabad district"},
    {"Bhongir":"	Yadadri Bhuvanagiri district"},
    {"Chevella":"	Rangareddy district"},
    {"Hyderabad":"	Hyderabad district"},
    {"Karimnagar":"	Karimnagar district"},
    {"Khammam":"	Khammam district"},
    {"Mahabubabad":"	Warangal (Rural) and Bhadradri Kothagudem districts"},
    {"Malkajgiri":"	Medchal-Malkajgiri district"},
    {"Medak":"	Medak district"},
    {"Nagarkurnool":"	Nagarkurnool district"},
    {"Nalgonda":"	Nalgonda district"},
    {"Nizamabad":"	Nizamabad district"},
    {"Peddapalle":"	Peddapalli district"},
    {"Secunderabad":"	Hyderabad district"},
    {"Warangal":"	Warangal (Urban) and Warangal (Rural) districts"},
    {"Zahirabad":"	Sangareddy district"},
    {"Nizamabad":"	Nizamabad district"}]},
    {"id":25,"de":[{"Tripura East":	"East Tripura district"},
    {"Tripura West":"	West Tripura district"}]},
    {"id":26,"de":[{"Saharanpur":"Saharanpur"},
    {"Kairana":"Shamli, Saharanpur, Muzaffarnagar"},
    {"Muzaffarnagar":"Muzaffarnagar"},
    {"Bijnor":"	Bijnor"},
    {"Nagina":"	Bijnor, Moradabad, Amroha"},
    {"Moradabad":"	Moradabad"},
    {"Rampur":"	Rampur"},
    {"Sambhal":"	Sambhal, Moradabad"},
    {"Amroha":"	Amroha"},
    {"Meerut":"	Meerut"},
    {"Baghpat":"	Baghpat"},
    {"Ghaziabad	":"Ghaziabad"},
    {"Gautam Buddha Nagar":"	Gautam Buddha Nagar"},
        {"Bulandshahr":"	Bulandshahr"},
        {"Aligarh":"	Aligarh"},
        {"Hathras":"	Hathras, Aligarh"},
        {"Mathura":"	Mathura"},
        {"Agra":"	Agra"},
        {"Fatehpur Sikri":"	Agra, Firozabad"},
        {"Firozabad":"	Firozabad"},
        {"Mainpuri":"	Mainpuri"},
        {"Etah":"	Etah"},
        {"Badaun":"	Badaun"},
        {"Aonla":"	Bareilly"},
        {"Bareilly":"	Bareilly"},
        {"Pilibhit":"	Pilibhit"},
        {" Shahjahanpur":"	Shahjahanpur"},
        {"Kheri":"	Kheri"},
        {"Dhaurahra":"	Lakhimpur Kheri"},
        {"Sitapur":"	Sitapur"},
        {"Hardoi":"	Hardoi"},
        {"Misrikh":"	Hardoi, Unnao, Lucknow"},
        {"Unnao":"	Unnao"},
        {"Mohanlalganj":"	Lucknow"},
        {"Lucknow":"	Lucknow"},
        {"Rae Bareli":"	Rae Bareli"},
        {"Amethi":"	Amethi"},
        {"Sultanpur":"	Sultanpur"},
        {"Pratapgarh":"	Pratapgarh"},
        {"Farrukhabad":"	Farrukhabad"},
        {"Etawah":"	Etawah"},
        {"Kannauj":"	Kannauj"},
        {"Kanpur":"	Kanpur Nagar"},
        {"Akbarpur":"	Kanpur Dehat, Kannauj, Auraiya"},
        {"Jalaun":"	Jalaun"},
        {"Jhansi":"	Jhansi"},
        {"Hamirpur":"	Hamirpur"},
        {"Banda":"	Banda"},
        {"Fatehpur":"	Fatehpur"},
        {"Kaushambi":"	Kaushambi"},
        {"Phulpur":"	Allahabad"},
        {"Allahabad	":"Allahabad"},
        {"Barabanki":"	Barabanki"},
        {"Faizabad":"	Faizabad"},
        {"Ambedkar Nagar":"	Ambedkar Nagar"},
        {"Bahraich":"	Bahraich"},
        {"Kaiserganj":"	Bahraich, Sitapur, Barabanki"},
        {"Shrawasti":"	Shrawasti"},
        {"Gonda":"	Gonda"},
        {"Domariyaganj":"	Siddharthnagar, Basti, Sant Kabir Nagar"},
        {"Basti":"	Basti"},
        {"Sant Kabir Nagar":"	Sant Kabir Nagar"},
        {"Maharajganj":"	Maharajganj"},
        {"Gorakhpur":"	Gorakhpur"},
        {"Kushinagar":"	Kushinagar"},
        {"Deoria":"	Deoria"},
        {"Bansgaon":"	Gorakhpur, Maharajganj"},
        {"Lalganj":"	Azamgarh, Ghazipur, Ballia"},
        {"Azamgarh":"	Azamgarh"},
        {"Ghosi	Mau": "Ghazipur, Ballia"},
        {"Salempur":"	Deoria, Ghazipur"},
        {"Ballia":"	Ballia"},
        {"Jaunpur":"	Jaunpur"},
        {"Machhlishahr":"	Jaunpur, Bhadohi, Mirzapur"},
        {"Ghazipur":"	Ghazipur"},
        {"Chandauli":"	Chandauli"},
        {"Varanasi":"	Varanasi"},
        {"Bhadohi":"	Bhadohi"},
        {"Mirzapur":"	Mirzapur"},
        {"Robertsganj":"	Sonbhadra"}]},
    {"id":27,"de":[{"Almora":"Almora district"},
    {"Garhwal":"	Pauri Garhwal district"},
    {"Hardwar":"	Haridwar district"},
    {"Nainital-Udhamsingh":" Nagar	Nainital and Udham Singh Nagar districts"},
    {"Tehri Garhwal":"	Tehri Garhwal district"}]},
    {"id":28,"de":[{"Cooch Behar":"Cooch Behar"},
    {"Alipurduars":"	Alipurduar"},
    {"Jalpaiguri":"	Jalpaiguri"},
    {"Darjeeling":"	Darjeeling"},
    {"Raiganj":"	Uttar Dinajpur"},
    {"Balurghat":"	Dakshin Dinajpur"},
    {"Maldaha":" Uttar	Malda"},
    {"Maldaha ":"Dakshin	Malda"},
    {"Jangipur":"	Murshidabad"},
    {"Baharampur":"	Murshidabad"},
    {"Murshidabad":"	Murshidabad"},
    {"Krishnanagar":"	Nadia"},
    {"Ranaghat":"	Nadia"},
    {"Bangaon":"	North 24 Parganas"},
    {"Barrackpore":"	North 24 Parganas"},
    {"Dum Dum":"	North 24 Parganas"},
    {"Barasat":"	North 24 Parganas"},
    {"Basirhat":"	North 24 Parganas"},
    {"Jaynagar":"	South 24 Parganas"},
    {"Mathurapur":"	South 24 Parganas"},
    {"Diamond Harbour":"	South 24 Parganas"},
    {"Jadavpur":"	Kolkata, South 24 Parganas"},
    {"Kolkata Dakshin":"	Kolkata"},
    {"Kolkata Uttar":"	Kolkata"},
    {"Howrah":"	Howrah"},
    {"Uluberia":"	Howrah"},
        {"Hooghly":"	Hooghly"},
        {"Arambagh":"	Hooghly"},
        {"Tamluk":"	Purba Medinipur"},
        {"Kanthi":"	Purba Medinipur"},
        {"Ghatal":"	Paschim Medinipur"},
        {"Jhargram":"	Jhargram, Paschim Medinipur"},
        {"Medinipur":"	Paschim Medinipur"},
        {"Purulia":"	Purulia"},
        {"Bankura":"	Bankura"},
        {"Bishnupur":"	Bankura"},
        {"Bardhaman Purba":"	Purba Bardhaman"},
        {"Bardhaman Durgapur":"	Paschim Bardhaman"},
        {"Asansol":"	Paschim Bardhaman"},
        {"Bolpur":"	Birbhum"},
        {"Birbhum":"	Birbhum"}]},
    {"id":29,"de":[{"Andaman and Nicobar Islands":"Entire union territory"}]},
    {"id":30,"de":[{"Chandigarh":"Entire union territory"}]},
    {"id":31,"de":[{"Dadra and Nagar Haveli and Daman and Diu":"Entire union territory"}]},
    {"id":32,"de":[{"Lakshadweep":"Entire union territory"}]},
    {"id":33,"de":[{"Chandni Chowk":"North Delhi district and parts of North West Delhi district"},
    {"East Delhi":"	East Delhi district"},
    {"New Delhi	Central":" Delhi district and parts of South Delhi district"},
    {"North East Delhi":"	North East Delhi district"},
    {"North West Delhi":"	North West Delhi district"},
    {"South Delhi":"	South Delhi district"},
    {"West Delhi":"West Delhi district"}]},
    {"id":34,"de":[{"Puducherry":"Entire union territory"}]}]
const stateWiseDetails= [{id:1,name:"Andhra Pradesh", constituencies:25},{id:2,name:"Arunachal Pradesh", constituencies:2},{id:3,name:"Assam",constituencies:14},{id:4,name:"Bihar", "constituencies":"40"},{id:5,name:"Chattisgarh", "constituencies":"11"},{id:6,name:"Goa", "constituencies":"2"},{id:7,name:"Gujarat", "constituencies":"26"},{id:8,name:"Haryana", "constituencies":"10"},{id:9,name:"Himachal Pradesh", "constituencies":"4"},{id:10,name:"Jharkhand", "constituencies":"14"},{id:11,name:"Karanataka", "constituencies":"28"},{id:12,name:"Kerala", "constituencies":"20"},{id:13,name:"Madhya Pradesh", "constituencies":"29"},{id:14,name:"Maharashtra", "constituencies":"48"},{id:15,name:"Manipur", "constituencies":"2"},
    {id:16,name:"Meghalaya", "constituencies":"2"},{id:17,name:"Mizoram", "constituencies":"1"},{id:18,name:"Nagaland", "constituencies":"1"},{id:19,name:"Odisha", "constituencies":"21"},{id:20,name:"Punjab", "constituencies":"13"},{id:21,name:"Rajasthan", "constituencies":"25"},{id:22,name:"Sikkim", "constituencies":"1"},{id:23,name:"Tamilnadu", "constituencies":"39"},{id:24,name:"Telangana", "constituencies":"17"},{id:25,name:"Tripura", "constituencies":"2"},{id:26,name:"Uttar Pradesh", "constituencies":"80"},{id:27,name:"Uttarakhand", "constituencies":"5"},{id:28,name:"West Bengal", "constituencies":"42"},{id:29,name:"Andamon and Nicobar Islands", "constituencies":"1"},{id:30,"name":"Chandigarh", "constituencies":"1"},{id:31,name:"Dadra and Nagar Haveli and Daman and Diu", "constituencies":"1"},
    {id:32,name:"Lakshadweep", "constituencies":"1"},{id:"33",name:"Delhi", "constituencies":"7"},{id:34,name:"Puducherry", "constituencies":"1"}]

class App extends Component {
  state ={mpList:List,newList:["hai"],stateWiseDetails:stateWiseDetails,data:data}

  onAddCandidate = data => {
    const {mpList,newList}=this.state
    this.setState({mpList:[...mpList,data]})
    console.log(mpList)
  }
  render(){
    const {mpList,items,stateWiseDetails,data}=this.state
    // const data=Cookies.get('newList')
  return(
    <ListContext.Provider value={{mpList:mpList,onAddCandidate:this.onAddCandidate}}>
    <BrowserRouter>
    <Routes>
      <Route  path="/" element={<Admin/>}/>
      <Route exact path="/mplist" element={<MpList stateWiseDetails={stateWiseDetails} data={data}/>} />
    </Routes>
    </BrowserRouter>
    </ListContext.Provider>
  )
  }
}

export default App;
